language: node_js
node_js:
    - "node"
    - "7"
before_install:
    - sudo apt-get install unixodbc unixodbc-dev
    - npm install
    - npm install -g mocha
    - npm run-script start &&
script:
  - npm run-script build
  - npm run-script test
