language: node_js
node_js:
    - "node"
    - "7"
before_install:
    - sudo apt-get install unixodbc unixodbc-dev
    - npm install
    - cp config.js.example config.js
    - sudo pip install lxml
script:
  - webpack
